plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    id 'com.gradleup.shadow' version '8.3.5'
}

String buildNumber = System.getenv("GITHUB_RUN_NUMBER")
version = "${mod_version}${buildNumber != null ? ".${buildNumber}" : ""}+mc${minecraft_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    gradlePluginPortal()
    mavenCentral()
    mavenLocal()

    // Forge
    maven { url 'https://maven.minecraftforge.net/' }

    // Parchment mappings
    maven { url 'https://maven.parchmentmc.org' }

    // Quilt
    maven { url 'https://maven.quiltmc.org/repository/release' }

    // ???
    // maven { url 'https://maven.blamejared.com' }

    // Sponge mixins
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }

    // Create
    maven { url = "https://maven.createmod.net" }

    // Registrate
    maven { url = "https://maven.tterrag.com" }

    // ???
    // maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }

    // Modrinth
    maven {
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup 'maven.modrinth'
        }
    }

    // CurseForge
    maven {
        url = 'https://www.cursemaven.com'
        content {
            includeGroup "curse.maven"
        }
    }

    // Kotlin for Forge
    maven {
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }

    // Ritchie's Projectile Library, CBC
    maven {
        url = "https://maven.realrobotix.me/master/"
        content {
            includeGroup("com.rbasamoyai")
        }
    }

    // Valkyrien Skies
    maven { url = 'https://maven.valkyrienskies.org' }

    // ModMaven
    maven { url "https://modmaven.dev" }

    // CC: Tweaked
    maven {
        name = "squiddev"
        url = "https://squiddev.cc/maven/"
    }

}

dependencies {
    // Forge stuff
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly fg.deobf("maven.modrinth:architectury-api:${architectury_api_version}+forge")

    compileOnly "thedarkcolour:kotlinforforge:${forge_kotlin_version}"

    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    // JEI
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    // Create and it's addons
    implementation fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    runtimeOnly fg.deobf("com.simibubi.create:create-${minecraft_version}:${create_version}")

    implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")

    implementation fg.deobf("com.jozufozu.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")

    compileOnly fg.deobf("maven.modrinth:trackwork:${minecraft_version}-${trackwork_version}")

    // CBC
    implementation fg.deobf("com.rbasamoyai:ritchiesprojectilelib:${rpl_version}") { transitive = false }
    runtimeOnly fg.deobf("com.rbasamoyai:ritchiesprojectilelib:${rpl_version}") { transitive = false }

    implementation fg.deobf("com.rbasamoyai:createbigcannons:${cbc_version}") { transitive = false }
    runtimeOnly fg.deobf("com.rbasamoyai:createbigcannons:${cbc_version}") { transitive = false }

//    compileOnly fg.deobf("maven.modrinth:cbcmodernwarfare:${cbc_mw_version}+mc.${minecraft_version}-forge")
    implementation fg.deobf("curse.maven:cbc-modern-warfare-1078220:6262257")

//    compileOnly fg.deobf("maven.modrinth:create-big-cannons-advanced-technologies:${cbc_at_version}-${minecraft_version}")
    implementation fg.deobf("curse.maven:create-big-cannons-advanced-technologies-1180196:6431936")

    // Valkyrien Skies

    compileOnly("org.valkyrienskies.core:api-game:${vs_core_version}")
    compileOnly("org.valkyrienskies.core:api:${vs_core_version}")
    compileOnly("org.valkyrienskies.core:impl:${vs_core_version}")
    compileOnly("org.valkyrienskies.core:util:${vs_core_version}")
    compileOnly fg.deobf("org.valkyrienskies:valkyrienskies-120-forge:${vs2_version}")

    compileOnly fg.deobf("maven.modrinth:create-clockwork:${minecraft_version}-${clockwork_version}")

    // CC: Tweaked
    compileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-core-api:${cc_tweaked_version}")
    compileOnly fg.deobf("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cc_tweaked_version}")
    runtimeOnly fg.deobf("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cc_tweaked_version}")

    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"

    // Additional libraries
    implementation "org.apache.commons:commons-math3:3.6.1"
    runtimeOnly "org.apache.commons:commons-math3:3.6.1"
    compileOnly "org.joml:joml:1.10.5"
    compileOnly "com.fasterxml.jackson.core:jackson-annotations:2.13.3"
}

mixin {
    add sourceSets.main, 'createradar.refmap.json'
    config 'create_radar.mixins.json'
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            forge_version       : forge_version, forge_version_range: forge_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
            mod_authors         : mod_authors, mod_description: mod_description, create_version_range: create_version_range
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'MixinConfigs'            : 'create_radar.mixins.json'
        ])
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
